### ISSUE TITLE
How Broker can send a message back to a publisher ?

### ISSUE THREAD

**Issue by Fbo06** [martin-ger/uMQTTBroker#15]
Hello, thirst thank you for sharing this code who is very useful. I have a question, how the broker could response to the publisher (who isn't on the local network ) because i don't see any reference to the "client". 
for example a mosquito "client" send this 
   mosquitto_pub -m "Relay ON" -t "/MyMQTT_Sub" -h "192.168.1.96"
The broker well receive the message
and now i want to send back (from the broker) a acknowledge message like "OK the Relay is switch ON".
thank you for your response

**Comment by martin-ger** [comment]
The broker can also publish a message with a topic and if the client has subscribed for that topic, it will receive it. In MQTT there is no concept of a direct reply, but it is all done via pub/sub on topics,

If you look into the sample code: in line 86 there is a publish of the broker. If your client subscribes with:
`mosquitto_sub -d -t "/MyBroker/count" -h "192.168.1.96"`
it will receive these messages.

**Comment by Fbo06** [comment]
Thank you Martin-ger, i understand the concept of pub/sub on topics but why we can't use the "Client" object ?

**Comment by Fbo06** [comment]
Another time thank you for your support.
