### ISSUE TITLE
user_interface.h: No such file or directory

### ISSUE THREAD

**Issue by AlirezaSadri** [martin-ger/uMQTTBroker#17]
Hi

I added uMQTTBroker to my Sloeber project and I am receiving this error. Can please tell me what I am missing? (I managed to test PubSubClient succefully). also can I test on a ESP32?

Best regards

**Comment by wyojustin** [comment]
Same issue for me.

**Comment by martin-ger** [comment]
Do you have the esp8266 board support package installed? For me it compiles well with Arduino 1.8.5 and ESP 2.4.2 (latest).

**Comment by wyojustin** [comment]
AlirexaSadri and I are attempting to use this with ESP32.  I decided to use websockets for now, so this is not an issue for me any more.

**Comment by martin-ger** [comment]
Okay, the library doesn't work for the ESP32 (yet?) - see #13

**Comment by wyojustin** [comment]
Thank you for your prompt response!
