### ISSUE TITLE
Compiler Error EXFUN

### ISSUE THREAD

**Issue by sochs** [martin-ger/uMQTTBroker#19]
Hello,

great work! Unfortunately, I get an error message when compiling (Arduino IDE 1.8.7, I also tested 1.8.5 and 1.6.11). The error occurs as soon as I add #include "uMQTTBroker.h" to any project (even uMQTTBroker-Example).

Here is the complete error message. Maybe you have some advice for me.

             In file included from C:\Users\xxx\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0/tools/sdk/include/os_type.h:10:0,
                 from C:\Users\xxx\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0/tools/sdk/include/user_interface.h:9,

                 from C:\Users\xxx\Documents\Arduino\libraries\uMQTTBroker\src\uMQTTBroker.h:4,

                 from C:\Users\xxx\Documents\Arduino\libraries\uMQTTBroker\src\uMQTTBroker.cpp:2:

             C:\Users\xxx\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0/tools/sdk/include/ets_sys.h:168:5: error: previous declaration of 'int atoi(const char*)' with 'C++' linkage

             int atoi(const char *nptr);

                 ^

             In file included from c:\users\xxx\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2\xtensa-lx106-elf\include\stdint.h:12:0,

                 from c:\users\xxx\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2\lib\gcc\xtensa-lx106-elf\4.8.2\include\stdint.h:9,

                 from C:\Users\xxx\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0/tools/sdk/include/c_types.h:8,

                 from C:\Users\xxx\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0/tools/sdk/include/ets_sys.h:11,

                 from C:\Users\xxx\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0/tools/sdk/include/os_type.h:10,

                 from C:\Users\xxx\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0/tools/sdk/include/user_interface.h:9,

                 from C:\Users\xxx\Documents\Arduino\libraries\uMQTTBroker\src\uMQTTBroker.h:4,

                 from C:\Users\xxx\Documents\Arduino\libraries\uMQTTBroker\src\uMQTTBroker.cpp:2:

             c:\users\xxx\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2\xtensa-lx106-elf\include\stdlib.h:70:5: error: conflicts with new declaration with 'C' linkage

             int _EXFUN(atoi,(const char *__nptr));

                  ^

             exit status 1
             Fehler beim Kompilieren für das Board Generic ESP8266 Module.

**Comment by cristiandc** [comment]
> An update to esp v2.4.0 solves the problem

hi! can u please tell me how to update to esp v2.4.0?
