### ISSUE TITLE
Error building with Platformio - Multiple ways to build

### ISSUE THREAD

**Issue by PRO2XY** [martin-ger/uMQTTBroker#2]
When building the example program on Platformio, the following error is thrown:

> *** Multiple ways to build the same target were specified for: C:\Users\username\Documents\PlatformIO\ESP8266_MQTT_Broker\.pioenvs\esp12e\lib\uMQTTB
roker-master\MQTT.o  (from ['C:\\Users\\username\\Documents\\PlatformIO\\ESP8266_MQTT_Broker\\lib\\uMQTTBroker-master\\src\\MQTT.cpp'] and from ['C:
\\Users\\username\\Documents\\PlatformIO\\ESP8266_MQTT_Broker\\lib\\uMQTTBroker-master\\src\\MQTT.c'])
File "C:\Users\username\.platformio\penv\lib\site-packages\platformio\builder\tools\platformio.py", line 272, in BuildLibrary

This might be due to the same name (mqtt.c and MQTT.cpp) of the two files being referenced, due to the non-case-sensitive nature of files on Windows. Both mqtt.c and MQTT.cpp would make the same object file, MQTT.o.

Possible solution, change MQTT.cpp (and .h) to MQTT_Broker.cpp? Along with changing the class name and constructor and destructor? Or is that not a good way to deal with this issue?

**Comment by martin-ger** [comment]
No experience with PlatformIO, but if it is just the name, changing it is probably the best solution. However, the two Files MQTT.h and MQTT.cpp are NOT implementing the broker (this is uMQTTBroker.h and the file in the mqtt-dir). These are just the C++ interface to the client functions. Thus, if you only need the broker, dropping the two files might also be an option.

**Comment by PRO2XY** [comment]
Ok! Thanks Martin. 
I would just rename them to MQTT_Client instead. Do these provide the functions for the local client as well? In which case I would have use for them. 
Are the 'MQTT_SetUserId' and 'MQTT_SetUserPwd', introduced in d54abcb, derived from these two files?

**Comment by martin-ger** [comment]
All you need to interact with the local MQTT broker is in uMQTTBroker.h. The current MQTT.h/cpp are just required when you want to use the "original" functionality of tuanpmt's CLIENT lib (client to a remote broker), that is still included.

If you want to check username/password for any client connecting to your local broker, use the callbacks:
```
typedef bool (*MqttAuthCallback)(const char* username, const char *password, struct espconn *pesp_conn);

void MQTT_server_onAuth(MqttAuthCallback authCb);
```
and return true if you are willing to accept this u/p.

**Comment by PRO2XY** [comment]
Thanks for the info Martin. 
I was able to compile successfully without the MQTT.cpp/.h on PlatformIO. The local client works well. Thanks for providing this helpful library.

**Comment by PRO2XY** [comment]
May I also suggest putting this information on the Readme, for other users who may face the same error on Platformio.
