### ISSUE TITLE
How to do a function if reveice then publish?

### ISSUE THREAD

**Issue by HoerMirAuf** [martin-ger/uMQTTBroker#21]
Hi ...

okay, i m playing around a little bit with the mqtt broker examples.

but how can i evaluate the received date in the void loop function?

if recevied a Message eval to a string do publish anything?
(ok, publishing isn't the problem myBroker.publish("", "") but how to get the recieved Value to a String?)

**Comment by martin-ger** [comment]
First processing can be done in the "onData" callback function (e.g. in the "OOFull" sample).  It is called on each subscribed and received Topic. If you need it longer for processing, store a value in a status variable in this callback, check that in the main loop, and do processing there.

**Comment by HoerMirAuf** [comment]
Thank you for the Hint ...

i am sorry but i'm a beginner to Arduino Code ...

i tryed out with the OOFull example ...
there's a code line:
Serial.println:("received topic '"+topic ......

But it seems not to work? Serial monitor keeps empty? Only the Standart Messages like IP, Starting MQtt Broker etc...
If i understand right there should be all received messages?

**Comment by martin-ger** [comment]
Yes, it should print any received topic, especially the counter values of the sample.
