### ISSUE TITLE
double receive a toggle command?

### ISSUE THREAD

**Issue by HoerMirAuf** [martin-ger/uMQTTBroker#24]
Hi there,

maybe someone can explain me this behavior:
Retained is disabled in the broker, respectively "0"
If i'm sending a toggle command by the uMQTT Broker, a listening mosquitto client, will show only this one toggle command, but the destination device (aTasmota Device) show the toggle twice in the log and it's also toggling twice ....

Is that a bug in the Broker? Or why the device get the command twice?

**Comment by martin-ger** [comment]
I am not aware of such a bug. Is there anything special in the code of the broker? Just the basic sample or local subscriptions/publications? What are the subscriptions of the Tasmota? Maybe two machting topics?

**Comment by HoerMirAuf** [comment]
I take the uMQTTBrokerSampleOOFull.

The only changes i have done in the Sample Code is a static IP, and deleted the counter publishing:

/*
 * uMQTTBroker demo for Arduino (C++-style)
 * 
 * The program defines a custom broker class with callbacks, 
 * starts it, subscribes locally to anything, and publishs a topic every second.
 * Try to connect from a remote client and publish something - the console will show this as well.
 */

#include <ESP8266WiFi.h>
#include "uMQTTBroker.h"

/*
 * Your WiFi config here
 */
char host[] = "ESP-MQTT";           // Hostname & SSID in AP-Mode
char ssid[] = "DEG-TEST-WLAN";      // your network SSID (name)
char pass[] = "12345678";           // your network password
bool WiFiAP = false;      // Do yo want the ESP as AP?
bool STATIC = true;                 // Static IP for STA Mode?
IPAddress ip(192,168,1,200);        // Static IP
IPAddress gw(192,168,1,1);          // Static Gateway/DNS
IPAddress su(255,255,255,0);        // Static Subnet Mask

/*
 * Custom broker class with overwritten callback functions
 */
class myMQTTBroker: public uMQTTBroker
{
public:
    virtual bool onConnect(IPAddress addr, uint16_t client_count) {
      Serial.println(addr.toString()+" connected");
      return true;
    }
    
    virtual bool onAuth(String username, String password) {
      Serial.println("Username/Password: "+username+"/"+password);
      return true;
    }
    
    virtual void onData(String topic, const char *data, uint32_t length) {
      char data_str[length+1];
      os_memcpy(data_str, data, length);
      data_str[length] = '\0';
      
      Serial.println("received topic '"+topic+"' with data '"+(String)data_str+"'");
    }
};

myMQTTBroker myBroker;

/*
 * WiFi init stuff
 */
void startWiFiClient()
{
  if (STATIC) {
	WiFi.config(ip, gw, gw, su);
  }
  WiFi.softAPdisconnect(true);
  WiFi.hostname(host);
  Serial.println("Connecting to "+(String)ssid);
  WiFi.begin(ssid, pass);
  
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.println(""); 
  Serial.println("WiFi connected");
  Serial.println("IP address: " + WiFi.localIP().toString());
  Serial.println(""); 
}

void startWiFiAP()
{
  WiFi.softAP(ssid, pass);
  Serial.println("AP started");
  Serial.println("IP address: " + WiFi.softAPIP().toString());
}

void setup()
{
  Serial.begin(115200);
  Serial.println();
  Serial.println();

  // Start WiFi
  if (WiFiAP)
    startWiFiAP();
  else
    startWiFiClient();

  // Start the broker
  Serial.println("Starting MQTT broker");
  myBroker.init();

/*
 * Subscribe to anything
 */
  myBroker.subscribe("#");
}

//int counter = 0;

void loop()
{
/*
 * Publish the counter value as String
 */
  //myBroker.publish("broker/counter", (String)counter++);
   
  // wait a second
  delay(1000);
}



The mosquitto_pub Topic is (the MQTT Device Name is "TEST", the Group Topic is the default "sonoff" but not used here):
mosquitto_pub -i LapTop -h 192.168.1.200 -t cmnd/TEST/POWER -m off
This command is only send once !!!

The debug webconsole log from tasmota show:
00:00:16 SRC: MQTT
00:00:16 RSL: Gruppe 0, Index 1, Befehl POWER, Daten off
00:00:16 MQT: stat/TEST/RESULT = {"POWER":"OFF"}
00:00:16 MQT: stat/TEST/POWER = OFF
00:00:16 SRC: MQTT
00:00:16 RSL: Gruppe 0, Index 1, Befehl POWER, Daten off
00:00:17 MQT: stat/TEST/RESULT = {"POWER":"OFF"}
00:00:17 MQT: stat/TEST/POWER = OFF

Every Command seems to result in a double publishing ??

**Comment by martin-ger** [comment]
Could you try to flash my https://github.com/martin-ger/esp_mqtt ?

It is the same core as the uMQTTBroker and you have much more debugging features. Especially you can see all subscriptions with "show mqtt" on the serial console. My guess is still, that the client has two subscriptions that match the topic.

**Comment by martin-ger** [comment]
The esp_mqtt includes binaries - no need to compile it - just flashing required.

QoS might be an issue - uMQTTBroker just suports QoS 0. QoS 1 or 2 might be undefined.

**Comment by HoerMirAuf** [comment]
Hi martin-ger.

Thank you very much for your patience and your help !!!

I was playing around with the Tasmota MQTT settings and found the Problem.... and .. your are right !!

In Tasmota it's possible die give a MQTT Topic Name and there are also a MQTT "Full-Topic" Name.
If the "Full-Topic" keep empty it will generated from a prefix AND the Topic.
So, there is a subscribtion with the same content parts twice !

Changing the "Full-Topic" Part to the right content and not the "Topic" your uMQTTBroker works fantastic.

The courios ... with other Brokers like IOBroker or Mosquitto this settings wasn't neccessary.

>  just flashing required.

... hmm will give them a try, but it is possible on a 1MB flash Memory??

**Comment by martin-ger** [comment]
Maybe we are interpreting the MQTT spec differently - maybe I am wrong and it should be delivered just once in such a case - have to dig a bit.

The esp_mqtt will work on 1 MB - I usually ran it on a Sonoff. However, if the Arduino version is fine for you and you don't need the additional features there, there is nothing wrong with it. The MQTT lib is the same.
