### ISSUE TITLE
Can not connect to AP in examples

### ISSUE THREAD

**Issue by d0h0** [martin-ger/uMQTTBroker#25]
I uploaded the examples to my NodeMCU. After updating my Arduino environment it worked like a charm, but connecting to the AP was not possible. 

```
AP started
IP address: 192.168.4.1
Starting MQTT broker
received topic 'broker/counter' with data '0'
received topic 'broker/counter' with data '1'
received topic 'broker/counter' with data '2'
```

When adding WiFi.mode(WIFI_AP); to the startWiFiAP method, remote connection were possible. So I wanted to make a pull request from my branch, but I failed here :)

So here is my suggestion to update this method in your examples like so:
```
void startWiFiAP()
{
  WiFi.mode(WIFI_AP);
  WiFi.softAP(ssid, pass);
  Serial.println("AP started");
  Serial.println("IP address: " + WiFi.softAPIP().toString());
}
```

Thank you for that great work!

**Comment by martin-ger** [comment]
Thank you for that hint. Added it to the repo.

**Comment by d0h0** [comment]
Great, thx!
