### ISSUE TITLE
MQTT_DEBUG_ON - how to get debug messages

### ISSUE THREAD

**Issue by RibeiroSantos** [martin-ger/uMQTTBroker#44]
Hi, 

I'm trying to get all MQTT_INFO messages but without success. How can I get them on serial output?

Thanks a lot

**Comment by martin-ger** [comment]
Think, os_printf() doesnt work in Arduino, you should change the define in mqtt/debud.h. Don't remember right noe what should go there.

**Comment by RibeiroSantos** [comment]
Ok, thanks.


The only way to debug when receiving any data (topic) is to use a onData
callback and then broker.subscribe("#")...
So, I'm trying to get other/better way.

A domingo, 30/08/2020, 12:17, martin-ger <notifications@github.com>
escreveu:

**Comment by pottendo** [comment]
hi, a quick hack:
#define MQTT_INFO printf
in mqtt/debug.h
makes it verbose.
bye, pottendo

**Comment by alka79** [comment]
Hi,
I defined MQTT_DEBUG_ON in my sketch and replaced os_printf by printf in mqtt/debug.h 
```
//#define MQTT_INFO( format, ... ) os_printf( format, ## __VA_ARGS__ )
#define MQTT_INFO( format, ... ) printf( format, ## __VA_ARGS__ )
```
that was supposed to be it, but nothing printed at all on Serial :(

So I hacked mqtt_server.c around line 44. It now looks like this : 
```
//#undef MQTT_INFO
//#define MQTT_INFO os_printf
//#define MQTT_WARNING os_printf
//#define MQTT_ERROR os_printf
#define MQTT_INFO printf
#define MQTT_WARNING printf
#define MQTT_ERROR printf
```

and I have them all printed Info, warning and error messages ! a lot of messages. lol.

**Comment by pottendo** [comment]
hi,
good to see someone is using uMQTTBroker... ;-)
I do have some stability issues on a 8266 (uMQTT broker + client) connected to a ESP32 (PubSub client) - I'd be happy to exchange experiences - maybe I open an issue here later today... however if you can share your experience I'd be happy to receive those - but maybe directly: pottendo AT gmx DOT net
thx pottendo

**Comment by RibeiroSantos** [comment]
I'm using it to play and try to deploy my own home automation system using
only esp8266 boards to control rollers/lamps/dimmer/alarm and esp32cams.

Until now I have a board acting as uMQTTBroker and same time as client with
2 switchs controling 2 220v lamps on/off with dimmer function. As clients
I'm using android app MQTT Dash.

Until now, even with 1 dimmer channel it is working fine.

A terça, 15/12/2020, 13:29, pottendo <notifications@github.com> escreveu:

**Comment by alka79** [comment]
I have opened another issue for optimization that is more inline with the discussion https://github.com/martin-ger/uMQTTBroker/issues/48

**Comment by RibeiroSantos** [comment]
Using #define MQTT_INFO as suggested
