### ISSUE TITLE
[ER] getClientCount , onDisconnectCb, getListOfClients

### ISSUE THREAD

**Issue by alka79** [martin-ger/uMQTTBroker#49]
The broker is quite shy and does not expose much of himself ! only onConnect and onAuth.
(onData is actually not exposed by the server but the local client subscriptions.)

Obvisouly, the server stores internally a lot more. Maybe it could share some : 

Would it be possible to expose 
- getClientCount(), returns the number of clients currently connected. 
- onDisconnectCb, a callback function fired when a client is disconnected. with its clientID, IPaddress. 
- getListOfClients(), returns the list of connected clients in a user friendly fashion 

I could do the first myself. I tried the others but my skills are too limited to succeed.

In uMQTTBroker.h , add  
```
virtual uint16_t getClientCount();
```

in uMQTTBroker.cpp, add 
```
uint16_t uMQTTBroker::getClientCount() {
return MQTT_server_countClientCon();
}
```

**Comment by martin-ger** [comment]
Added some code...

**Comment by alka79** [comment]
Yeah :) :) 
I'll try the new features asap. (_... and look how you've implemented them in the code because I struggled ;-)_ )

**Comment by alka79** [comment]
Almost forgot to report : the new code works fine :)
I was hoping to have the client ID available in onConnect(). 
I tried `getClientId(getClientCount(), myClientID)` without success. It seems getClientId returns nothing until the client is actually connected, ie onConnect accepted the connexion.
Is there a trick ?

**Comment by martin-ger** [comment]
During onConnect() the request is not yet parsed, thus the clientID is not yet known. This is as early as the TCP request comes in. It is to avoid the allocation of any status info. You get the clientID later in onAuth().

**Comment by alka79** [comment]
onAuth() will do. Thanks for the tip :)
