### ISSUE TITLE
Client count

### ISSUE THREAD

**Issue by Sinix10** [martin-ger/uMQTTBroker#59]
Hello, 

I need to know how many clients are connected to the broker. 
In the tutorial it states the following:
"The number of currently connected clients (incl. the current one) is given in the client_count paramater. With this info you can reject too many concurrent connections."

How can I use this "client_count"? It is not stated how to use it.

Best Regards

**Comment by Sinix10** [comment]
@martin-ger 
Hello Martin,

Could you please enlighten me?

Thanks

**Comment by martin-ger** [comment]
Use "getClientCount()" from the uMQTTBroker class.

**Comment by Sinix10** [comment]
> Use "getClientCount()" from the uMQTTBroker class.

I put it in the class, but It´s giving a Vtable error below when compiling.

**c:/users/sinix/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\uMQTTBrokerSampleOOFull.ino.cpp.o: in function `Nextion::~Nextion()':

C:\Users\Sinix\AppData\Local\Temp\arduino_modified_sketch_939180/uMQTTBrokerSampleOOFull.ino:1140: undefined reference to `vtable for myMQTTBroker'

collect2.exe: error: ld returned 1 exit status

exit status 1

Erro ao compilar para a placa LOLIN(WEMOS) D1 R2 & mini.**

**Comment by martin-ger** [comment]
Look at this sample: https://github.com/martin-ger/uMQTTBroker/blob/384a62005b11623ab8edddee553fd19734437742/examples/uMQTTBrokerSampleOOFull/uMQTTBrokerSampleOOFull.ino#L48

**Comment by Sinix10** [comment]
> Look at this sample:
> 
> https://github.com/martin-ger/uMQTTBroker/blob/384a62005b11623ab8edddee553fd19734437742/examples/uMQTTBrokerSampleOOFull/uMQTTBrokerSampleOOFull.ino#L48

I followed the line 48 as you suggested, but the following functions are not declared:
getClientCount()
getClientAddr()
getClientId()

I can not compile yet.


Bellow is how I have the class:

class myMQTTBroker: public uMQTTBroker
{
public:

      
    virtual bool onConnect(IPAddress addr, uint16_t client_count) {
      Serial.println(addr.toString()+" connected");
      Serial.write(0xff);
      Serial.write(0xff);
      Serial.write(0xff);
      
      MQTTclientcount ++;

      return true;
    }
    virtual void onDisconnect(IPAddress addr, String client_id) {
      Serial.println(addr.toString()+" disconnected");

       MQTTclientcount --;
       
    }

    virtual bool onAuth(String username, String password) {
      Serial.println("Username/Password: "+username+"/"+password);
      Serial.write(0xff);
      Serial.write(0xff);
      Serial.write(0xff);
      return true;
    }

    virtual void onData(String topic, const char *data, uint32_t length) {
      char data_str[length+1];
      ets_memcpy(data_str, data, length);
      data_str[length] = '\0';

      //Serial.println("received topic '"+topic+"' with data '"+(String)data_str+"'");

      if (topic == "Test/sensorT1"){
        T1 = data_str;
    }
      if (topic == "Test/sensorH1"){
        H1 = data_str;
    }
        if (topic == "Test/sensorT2"){
        T2 = data_str;
    }
      if (topic == "Test/sensorH2"){
        H2 = data_str;
    }
      if (topic == "Test/sensorT3"){
        T3 = data_str;
    }
      if (topic == "Test/sensorH3"){
        H3 = data_str;
    }
     if (topic == "Test/sensorT4"){
        T4 = data_str;
    }
      if (topic == "Test/sensorH4"){
        H4 = data_str;
    }
    if (topic == "Test/sensorT5"){
        T5 = data_str;
    }
      if (topic == "Test/sensorH5"){
        H5 = data_str;
    }
        if (topic == "Test/sensorT6"){
        T6 = data_str;
    }
      if (topic == "Test/sensorH6"){
        H6 = data_str;
    }
      if (topic == "Test/sensorT7"){
        T7 = data_str;
    }
      if (topic == "Test/sensorH7"){
        H7 = data_str;
    }
     if (topic == "Test/sensorT8"){
        T8 = data_str;
    }
      if (topic == "Test/sensorH8"){
        H8 = data_str;
    }
    
  }
  
  virtual void printClients() {
      for (int i = 0; i < getClientCount(); i++) {
        IPAddress addr;
        String client_id;
         
        getClientAddr(i, addr);
        getClientId(i, client_id);
        Serial.println("Client "+client_id+" on addr: "+addr.toString());
      }
    }
  
};
myMQTTBroker myBroker;

**Comment by martin-ger** [comment]
This is the implementation: https://github.com/martin-ger/uMQTTBroker/blob/384a62005b11623ab8edddee553fd19734437742/src/uMQTTBroker.cpp#L68

**Comment by Sinix10** [comment]
I´m sorry mate, but this is not being easy.
I thought the lib would have all those functions, but the files are not like that. Why?
I still can´t get it to work, what am I suppose to do over line 68?

**Comment by martin-ger** [comment]
It is all included. Did you use the correct installation procedure:
"Just clone (or download the zip-file and extract it) into the libraries directory of your Arduino ESP8266 installation."?

**Comment by Sinix10** [comment]
> It is all included. Did you use the correct installation procedure: "Just clone (or download the zip-file and extract it) into the libraries directory of your Arduino ESP8266 installation."?

I´m sorry brother, I now know ehat was the issue, my library was not updated, it´s all working perfectly.

Thanks brother.
