### ISSUE TITLE
Compiling error using uMQTTBroker

### ISSUE THREAD

**Issue by Sungapelke** [martin-ger/uMQTTBroker#70]
Hello,

I got an error message while including uMQTTBroker in a ESP32 project.

"C:\Users\uwebe\OneDrive\Workbench\Arduino\libraries\uMQTTBroker-master\src/uMQTTBroker.h:4:28: fatal error: user_interface.h: No such file or directory"

What is the problem here?
Please give me a solution.
Thanks in advance.

**Comment by martin-ger** [comment]
Sorry, the ESP32 is not supported by this lib.
